In [2]:
a = [3, 4, 5]
b = (a, 9)
b[0][2] = 8
print(a)

[3, 4, 8]


In [4]:
import numpy as np

def Fitness(indiv):
    return np.random.randint(100)

In [5]:
def GeneratorPopulaion(sizePop, dims):
    Populaion = []
    for i in range(sizePop):
        pi = np.random.permutation(range(1, dims))
        f_pi = Fitness(pi)
        Populaion.append((pi, f_pi))

    return Populaion

In [6]:
pop = GeneratorPopulaion(10, 10)
pop.sort(key=lambda tup: tup[1], reverse = False)
pop

[(array([3, 1, 8, 7, 2, 6, 5, 4, 9]), 24),
 (array([3, 1, 6, 5, 7, 8, 9, 2, 4]), 28),
 (array([4, 5, 8, 1, 7, 2, 6, 3, 9]), 29),
 (array([1, 3, 9, 8, 4, 6, 7, 5, 2]), 38),
 (array([5, 6, 8, 2, 9, 3, 1, 4, 7]), 56),
 (array([9, 1, 2, 4, 5, 8, 6, 7, 3]), 56),
 (array([3, 2, 8, 7, 5, 9, 1, 6, 4]), 67),
 (array([7, 4, 8, 2, 5, 9, 3, 6, 1]), 68),
 (array([6, 9, 8, 2, 3, 5, 7, 4, 1]), 75),
 (array([6, 3, 7, 4, 1, 8, 2, 5, 9]), 96)]